- name: Setup as service
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
- name: reload
  systemd:
    daemon_reload: yes
- name: Start as Service
  systemd:
    name: tomcat
    state: started
